version: '3.9'

services:
  backend:
    build: .
    container_name: django_app
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./core:/app
    environment:
      - SECRET_KEY=STRONG_SECRET_KEY_FOR_DEVELOPMENT
      - DEBUG=True
      - ALLOWED_HOSTS=*